name: Test

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: xcodebuild test -project UITestSample.xcodeproj -scheme UITestSample -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11 Pro"
